// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puzfettloxhfiuflxidp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1emZldHRsb3hoZml1Zmx4aWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDIwNDcsImV4cCI6MjA1MzM3ODA0N30.6oYiBSi7akOk_m8gN6P4ULTFtZfDdZtGbxJeMSfwLRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);